### ISSUE TITLE
error message ..

### ISSUE THREAD

**Issue by mohamadir** [studioidan/HttpAgent#9]
java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/os/AsyncTaskCompat;
        at com.studioidan.httpagent.HttpAgent.executeSelf(HttpAgent.java:173)
        at com.studioidan.httpagent.HttpAgent.goJson(HttpAgent.java:158)
        at com.example.snapgroup6.myapplication.MainActivity.onCreate(MainActivity.java:22)

**Comment by LostLite** [comment]
Encountered a similar error. Any progress towards the resolution of this?

**Comment by studioidan** [comment]
you can use the latest version of httpagent

בתאריך יום ב׳, 1 באוק׳ 2018, 0:13, מאת William Paul Muriuki ‏<
notifications@github.com>:
